# Имя рабочего процесса, которое будет отображаться в GitHub Actions
name: Build macOS App

# Условие запуска: запускать при любом push в репозиторий
on: [push]

jobs:
  build-macos:
    # Указываем, что сборка должна происходить на виртуальной машине с macOS
    runs-on: macos-latest

    steps:
      # Шаг 1: Клонируем код из вашего репозитория на виртуальную машину
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Шаг 3: Устанавливаем PyInstaller
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Шаг 4: Собираем приложение с помощью PyInstaller
      - name: Build macOS .app
        run: |
          # Указываем PyInstaller собрать ваш скрипт calculator.py
          # Опция --windowed убирает окно терминала
          pyinstaller --windowed --name="LicenseCalculator" calculator.py

      # Шаг 5: Загружаем собранное приложение как артефакт
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LicenseCalculator-macOS
          path: dist/LicenseCalculator.app # Путь к готовому .app пакету
