name: Build macOS App
on: [push]
jobs:
  build-macos:
    
    runs-on: macos-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      
      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      
      - name: Build macOS .app
        run: |
          # Указываем PyInstaller собрать ваш скрипт calculator.py
          # Опция --windowed убирает окно терминала
          pyinstaller --windowed --name="LicenseCalculator" calculator.py

      
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LicenseCalculator-macOS
          path: dist/LicenseCalculator.app # Путь к готовому .app пакету
